version: "3"

services:
  reader:
    build: reader/
    #command: tail -F anything
    expose:
      - "15672"
      - "5672"
      - "5432"
  sender:
    build: sender/
    command: tail -F anything
    expose:
      - "15672"
      - "5672"
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "15672"
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: vad
      RABBITMQ_DEFAULT_PASS: vad
  db:
    #build: sql/
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: vad
      POSTGRES_DB: vad
      POSTGRES_USER: vad
    expose:
      - "5432"
    volumes:
      - ./sql/sql1.sql:/docker-entrypoint-initdb.d/sql1.sql
      - ./sql/sql2.sql:/docker-entrypoint-initdb.d/sql2.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
